src/requirements.txt
New version of GOB-Core was needed for the generation of entity tables
and events, because of the use of GOB.DateTime
=> Update requirements, bump version of GOB-Core

src/.dockerignore, src/gobuploadservice/__main__.py, src/gobuploadservice/compare.py, src/gobuploadservice/storage/handler.py, src/requirements.txt, src/tests/fixtures.py, src/tests/test_compare.py, src/tests/test_main.py
Tables are now being generated on boot based on the gobcore model. The model is also used instead of metadata when comparing and updating the records.
=> Initialize database tables on boot

src/gobupload/__main__.py, src/gobupload/storage/__main__.py, src/gobupload/storage/handler.py
Scripts were added to be able to quickly truncate, drop or initialize the database or a single table. They can be started with:
python -m gobupload.storage drop <table>
python -m gobupload.storage drop --all
python -m gobupload.storage truncate <table>
python -m gobupload.storage truncate --all
python -m gobupload.storage init
=> Added storage scripts

src/gobupload/compare.py, src/gobupload/update.py
Alembic changes the default logging level
Declare the loggers in the compare and update methods re-enables
logging
=> Reenable logging

src/alembic/versions/29149a285ff2_change_json_to_jsonb.py, src/gobupload/relations.py, src/requirements.txt, src/tests/test_relations.py
We’ve switched to JSONB in the postgres database, but previously generated tables were still using JSON. This resulted in an error while trying to build relations on ManyReference fields. This alembic migration will change all columns to JSONB and updates the code to work for all relations. Views are dropped before the migration, but GOB-Upload recreates them on boot
=> Change all JSON columns to JSONB

src/alembic/versions/29149a285ff2_change_json_to_jsonb.py, src/gobupload/relations.py, src/tests/test_relations.py
ManyReferences with state did not relate properly because multiple records were returned. Now datum_einde_geldigheid is taken into account to make sure only the latest relation is made.
Also a small change was made to the migration to JSONB. Dropping views gave an error on an empty database so 'IF EXISTS' was added to fix this
=> Add state to ManyReferences

src/alembic/versions/9f515dab1ffb_rename_attributes_to_match_specs.py, src/gobupload/relations.py, src/gobupload/storage/handler.py, src/requirements.txt, src/tests/test_relations.py
A migration was added to rename the columns to match the latest specifications. Changes were made to rename ‘id’ to ‘identificatie’ and ‘datum_einde_geldigheid’ to ‘eind_geldigheid’
=> Renames to match latest specs

src/gobupload/update.py, src/tests/test_update.py
To prevent endless update loops
=> Stop processing when model is out of date

src/gobupload/storage/handler.py, src/gobupload/storage/queries.py, src/tests/storage/test_handler.py
Has states has been removed and compare is now done using _source_id. Creation of the temporary table has been simplified by using all_fields on the model
=> Removed has_states from compare

src/gobupload/storage/handler.py, src/gobupload/storage/queries.py, src/tests/storage/test_handler.py
Comparison was done on source_id but should’ve been on functional key fields.
=> Fix database compare query

src/gobupload/update.py, src/tests/test_update.py
The number of records which are stored and applied in a bulkconfirm event were missing from the results
=> Add bulkconfirm to upload results

src/gobupload/relate/relate.py, src/gobupload/storage/relate.py, src/tests/storage/test_relate.py
Include only non-deleted items
Skip empty items in relations, eg
- 2008-2008 => x1, None
- 2008-2009 => None
- 2009-2011 => x2
Becomes
- 2008-2008 => x1
- 2008-2009 => None
- 2009-2011 => x2
Allow for gaps in many-reference relations
=> Fix relate issues

src/gobupload/storage/handler.py
Indexes that exceed 8191 bytes cannot be created in PostgreSQL
=> Bugfix for large indexes

src/gobupload/compare/enrich.py, src/gobupload/update/update_statistics.py
Skipped events mean that events have been derived from
old entity states.
=> Treat skipped events as warnings

src/gobupload/storage/relate.py, src/tests/storage/test_relate.py
New way of relating using JSON lists may include strings within the JSON with single quotes.
=> Change string quotation in RelationUpdater

src/gobupload/storage/relate.py, src/tests/storage/test_relate.py
The order by was sorting ascending instead of ascending, resulting in unchanged relations after new events were added
=> Relate event order by descending

src/alembic/versions/21aa7c3e62b0_add_primary_key.py, src/gobupload/storage/relate.py, src/tests/storage/test_relate.py
Removing the primary key caused issues with automap in sqlalchemy. Therefor we’ve added a second order by key to bypass postgress choosing the wrong index
=> Re-add primary key and timestamp in query

src/gobupload/relate/__init__.py, src/gobupload/relate/apply.py, src/gobupload/relate/publish.py, src/gobupload/relate/relate.py, src/gobupload/storage/relate.py, src/tests/relate/test_apply.py, src/tests/relate/test_publish.py, src/tests/relate/test_relate.py, src/tests/storage/test_relate.py
Memory requirements of the relate process do no longer depend on the size of the collection
The whole process is streamed, based on the result of a query, and finally written
in a contents_ref file
=> Streaming relate

src/gobupload/update/event_applicator.py, src/gobupload/update/main.py, src/gobupload/utils.py, src/test.sh, src/tests/test_utils.py
Trigger garbage collection actively
To prevent any unnecessary memory consumption
=> Use active garbage collection

src/gobupload/__main__.py, src/gobupload/relate/__init__.py, src/gobupload/storage/relate.py, src/tests/relate/test_init.py, src/tests/storage/test_relate.py
If relations do not need any updates (because there was no change in any of the tables) all actions are skipped. This however also blocks any quality checks.
This PR proposes to always run all quality checks, even if the relations have not changed.
Any quality problems for static collections as gebieden will not get lost, but keep being reported
=> Relate key

src/gobupload/compare/main.py, src/tests/compare/test_compare.py
When comparing an entity with a changed _expiration_date the new date wasn’t seen as a change to the entity and thus resulting in a confirm event instead of a modify event. Comparisons now take all_fields in to account
=> Fix issue in compare

src/gobupload/__main__.py, src/tests/compare/test_main.py
Execute any migrations and then quit
=> Run migrate as a separate command

src/gobupload/storage/handler.py, src/tests/storage/test_handler.py, src/tests/storage/test_storage.py
Keep global data at class level
Use sessionmaker instead of Session
Initialize reflected base only once
close engine connection after statement has been executed
=> Reduce memory usage

src/gobupload/storage/handler.py, src/gobupload/update/event_applicator.py, src/tests/update/test_event_applicator.py
Events were not ordered by eventid when applying them to the database. The fix makes sure events are handled in order and event migration works for modify events
=> Fix event applicator for modify events

src/gobupload/__main__.py, src/gobupload/storage/handler.py, src/gobupload/storage/materialized_views.py, src/requirements.txt, src/tests/storage/test_handler.py, src/tests/storage/test_materialized_views.py, src/tests/test_main.py
Add functionality to force recreation of materialized views and indexes.
Update gobcore.
This PR can be merged without worrying about forcing recreation of materialized views. This has already been done on acc (from my local machine).
=> Update materialized views on relation tables with GOBID

src/tests/test_update.py
The tests used fixtures that generated random events.
Because of the new handling of CONFIRM events the tests failed
also randomly (or not)
=> Fix for random events

src/gobupload/apply/main.py, src/gobupload/compare/event_collector.py, src/gobupload/compare/main.py, src/gobupload/update/main.py, src/tests/compare/test_event_collector.py, src/tests/test_update.py
This eliminates the need to write confirm events twice:
- in the events file by compare
- in the confirms file by fullupdate
=> Let compare write confirm events directly in a confirms file

src/gobupload/storage/materialized_views.py, src/tests/storage/test_materialized_views.py
The functionality was disabled beacuse it lead to errors on the ACC environment
These errors have been fixed, so the functionality can be re-enabled
=> Re-enable indexes on materialized views

src/gobupload/relate/__init__.py
For relate jobs this resulted in a log record with ‘nap’ as both the catalog and collection which caused the frontend to try to start a relate job with ‘relate nap nap’ resulting in an error. When a job is started with only a catalog the collection will be NULL in the database
=> Fill entity with the collection instead of catalog

src/alembic/env.py, src/alembic/versions/ea556acbed92_events_partitioning.py, src/gobupload/storage/handler.py, src/gobupload/storage/relate.py, src/requirements.txt, src/tests/storage/test_relate.py
The migration of the current events table to the new partitioned events table will take approx 2 hours for 115.000.000 events.
The current events table is not deleted after migration. It will be deleted on a next migration.
=> Partitioned events table

src/gobupload/storage/handler.py, src/tests/storage/test_handler.py
Escape the input of the execute statement with the sqlalchemy.text function
=> Fix dict does not support indexing

src/gobupload/compare/enrich.py, src/gobupload/relate/table/update_table.py, src/tests/compare/test_enrich.py
When a current value is found in the storage
Update last assigned value if the current value is bigger then the last assigned value
=> Fix bug in autoid

src/gobupload/apply/main.py, src/gobupload/compare/main.py, src/gobupload/update/main.py
In order to process data from multiple sources in parallel
the application of events should also be bound to a source
This prevents that the one process applies already the events of another process
=> Apply bound to source if a source is specified

src/gobupload/apply/main.py, src/gobupload/compare/main.py, src/gobupload/update/main.py
In order to process data from multiple sources in parallel
the application of events should also be bound to a source
This prevents that the one process applies already the events of another process
=> Release apply bound to source if a source is specified

src/gobupload/apply/main.py
This prevents a WORKFLOW job on an empty collection
=> Always show always intro

src/gobupload/apply/main.py
This prevents a WORKFLOW job on an empty collection
=> Release always show always intro

src/gobupload/compare/entity_collector.py, src/gobupload/compare/main.py, src/gobupload/storage/handler.py, src/tests/storage/test_handler.py
To prevent collissions when running multiple compares
for the same catalog-collection for different sources
=> Use a temp table name for comparison

src/gobupload/compare/entity_collector.py, src/gobupload/compare/main.py, src/gobupload/storage/handler.py, src/tests/storage/test_handler.py
To prevent collissions when running multiple compares
for the same catalog-collection for different sources
=> Release use a temp table name for comparison

src/gobupload/relate/table/entrypoint.py, src/gobupload/relate/table/update_table.py, src/gobupload/storage/execute.py, src/tests/relate/table/test_update_table.py, src/tests/storage/test_execute.py
This PR is not a solution to the problem. I found however a few things to improve:
1. The max_row_buffer parameter was not used. The standard parameter is 1000 rows each which is rather limited for a 2M row table.
2. The logging was only showing the end, not the begin of the action. Makes it a little easier to detect the problem in the future.
3. Any failure resulted in a mystical dump without specifying the failing action. We do not have any tagging of ACC and PROD releases so it is unclear what the exact failing query is. The query is now printed on failure.
None of the fixes will probably fix the problem but as we don not have access to production data the logging should provide us with better clues to fix the problem.
=> Relate BAG verblijfsobjecten heeft hoofdadres fails

src/gobupload/storage/relate.py
From ticket:
"Dit zijn allemaal data warnings. Tevens klopt het aantal 27 niet, als de 25 warnings geen datameldingen zijn zouden er 26 warnings moeten staan (25 + die regel) en 51 datawarnings."
This PR handles the case for the 51 datawarnings. One of those 27 warnings is changed to a datwarning. Now the total warnings is indeed 26 and this job now returns 51 datawarnings (was 50).
=> PGB-975 Change 'missing referenced entity' warning to datawarning

src/gobupload/storage/relate.py
If a collection has no states then the volgnummer is None
The 'src_volgnummer' attribute does not exist in the conflicting row
=> Fix for missing src_volgnummer

src/gobupload/storage/relate.py
If a collection has no states then the volgnummer is None
The 'src_volgnummer' attribute does not exist in the conflicting row
=> Release fix for missing src_volgnummer

src/gobupload/apply/main.py, src/gobupload/storage/handler.py, src/gobupload/update/event_applicator.py, src/tests/update/test_event_applicator.py
Group events and apply the events in bulk
Instead of retrieving each entity, apply the event and flush per 1000 updates
Events are buffered, retrieved in bulk and applied and flushed per 10000
Performance improvement: 2 to 3 times faster than before
=> Improve performance of apply events

src/gobupload/compare/enrich.py, src/tests/compare/test_enrich.py
On partial imports, some records could already have been assigned a value on a previous run. This value was being used to determine the next value, but it would not necessarily be the highest value in the database. To prevent this, we will set the last value when the enricher is initialized
=> Fix the bug with auto id

src/gobupload/apply/main.py, src/tests/apply/test_apply.py
The DUMP wasn't triggered, because 'before' and 'after' were always equal. Both 'before' and 'after' were set based on the max event in the events table, but in apply these don't change. For DUMP, we are interested in the state of the object table. The max event id in the object table before and after applying events.
Example:
Say STORE events has stored events 0 to 100. The max event in the object table is 50. Before this PR, before = 100 and after = 100 would be returned, as the max event in the events table doesn't change in APPLY. Now before = 50 and after = 100 is returned.
=> Fix event ID's passed to EventNotification

src/gobupload/relate/update.py, src/tests/relate/test_update.py
- Inspect MODIFY events to better determine which objects to include in the update.
- Trigger initial relate when a large part of src and dst objects need to be re-inspected
=> PGB-1602 Improve relate

src/gobupload/__main__.py, src/gobupload/config.py, src/gobupload/dev_utils/relate_interval_table.py, src/gobupload/dev_utils/relate_query.py, src/gobupload/relate/update.py, src/tests/dev_utils/test_relate_interval_table.py, src/tests/dev_utils/test_relate_query.py, src/tests/relate/test_update.py
- Add OR clause in the relate to relate those objects.
- Extract Validities tmp table into its own class.
- Use extracted class in new command line tool to generate tmp tables in development environment.
=> PGB-1657: Relate objects with begin_geldigheid = eind_geldigheid.

src/gobupload/update/event_applicator.py, src/tests/update/test_event_applicator.py
When applying a batch with mulitple modify events, only one event would be applied. For a sequence of add->delete->add events for the same entity an error would be thown because the add events would be handled before the delete event.
=> Fix Eventapplicator for multiple events of the same entity

src/gobupload/compare/enrich.py, src/tests/compare/test_enrich.py
The `_geounion` needs to return None instead of a GeoType object. Otherwise the value can't be inserted in the db.
=> Handle empty result in `_geounion` enricher

src/requirements.txt
Don't think the bug would have caused problems in this repo, as this repo doesn't use the legacy feature for GOBModel. Just in case.
=> Update core with rel catalog fix

src/alembic/versions/5ab4ad3a4430_fix_nap_peilmerken_relation_events.py
Because these steps were not done properly when migrating NAP Peilmerken to AMS Schema. For Gebieden this is done properly with the appropriate helper functions.
This migration fixes the current issue with relations on acceptance and production and is idempotent.
=> Add migration to fix NAP Peilmerken relations in acc/prod

src/gobupload/relate/__init__.py, src/requirements.txt, src/tests/relate/test_init.py
Use warning instead of info, when a relation specification is missing. 
This way it will show up in Iris.
Updated core with new meetbouten relation names
=> Warn when relations are skipped in preparing relate

src/gobupload/__main__.py, src/gobupload/apply/main.py, src/gobupload/storage/handler.py, src/gobupload/update/event_applicator.py, src/gobupload/update/update_statistics.py, src/tests/apply/test_apply.py, src/tests/storage/test_handler.py, src/tests/storage/test_storage.py, src/tests/update/test_event_applicator.py
Main purpose of this PR is to use server-side cursor during the `apply` workflow.
Fixed some other things along the way.
- Rewrote queries using new sqlalchemy style (select() instead of query())
- Added limit(1) to .first() queries, only 1 row needed
- Added StreamSession to add `stream_execute` and `stream_scalars` functions
- Use StreamSession to fetch all the events instead of pagination
- During standalone mode, we need to log with log.error. Otherwise the program exits 0
- Removed returned applied events (not used anymore)
- ActiveGarbageCollection not needed anymore
Fixed [AB#64420](https://dev.azure.com/CloudCompetenceCenter/7755cdf4-1859-48c5-b954-fd6c8e46fe52/_workitems/edit/64420)
=> Apply event fixes

src/gobupload/__main__.py, src/gobupload/apply/main.py, src/gobupload/storage/handler.py, src/gobupload/update/event_applicator.py, src/gobupload/update/update_statistics.py, src/tests/apply/test_apply.py, src/tests/storage/test_handler.py, src/tests/storage/test_storage.py, src/tests/update/test_event_applicator.py
* Optimize apply_events
- Narrow session scope
- Remove unused returned events
- Use counter on other_events instead of calculating on every event
* Small fixes for `handler.py`
- according to doc geoalchemy2 must be imported when reflecting database
- correct import MultipleResultsFound
- use comprehension in add_add_events
- set query_size_cache to 250 to limit sqlalchemy cache use
* Use `self` in update_statistics.py
* Fix flake8 import in handler.py
* Add StreamSession class
* Add limit when querying with first()
* Add tests for handler.py and storage.py
* Add tests event_applicator.py and handler.py
* Add docstring + remove unused import
* Fix initialising connection for session
* Optimize yield_per size for memory
* Fix column attr get in case of None
* Remove legacy flush function …
=> Apply event fixes (#1011)

src/gobupload/__main__.py, src/tests/test_main.py
Instead make an explicit call to the `migrate` handler in a seperate job
=> In standalone mode, don't migrate as default

src/alembic/versions/0ce50938f539_gebieden_begin_eind_geldigheid_datetime.py, src/alembic/versions/529e01408f26_integer_volgnummer.py
If the citus extension is installed, skip dropping all view which start with citus_ to pass migrations
=> Exclude dropping citus views during migrations

src/gobupload/compare/entity_collector.py, src/gobupload/compare/main.py, src/gobupload/storage/handler.py, src/tests/compare/test_entity_collector.py, src/tests/storage/test_handler.py, src/tests/storage/test_storage.py
Use a postgresql TEMPORARY table for comparing data instead of a regular table.
Benefits:
- Dropped automatically at the end of the session
- Not WAL logged, so should be faster
- no naming collisions, temp table only visible to current session
- no other database sessions can interact with it
=> Use TEMPORARY table for compare

src/gobupload/apply/main.py, src/gobupload/compare/event_collector.py, src/gobupload/storage/handler.py, src/requirements.txt, src/tests/apply/test_apply.py, src/tests/storage/test_handler.py, src/tests/update/test_main.py
* Refactor apply_confirm_events
* Return early on empty confirms from message
* Fix: only set default value for `yield_per` if not set on connection yet
* Update Core
* Add tests for not overwriting yield_per from connection execution options
=> Refactor apply_confirm_events (#1020)

src/gobupload/compare/main.py, src/gobupload/storage/handler.py, src/tests/compare/test_compare.py
- remove dict conversion per row
- get MODIFY current entities only 1 time per chunk, not a query for every entity
- improve readability
=> Optimize process_compare_events

src/gobupload/storage/handler.py, src/requirements.txt, src/tests/storage/test_storage.py
Does not operate inplace for sqlalchemy < 2.0
=> Assign connection with execution_options

src/gobupload/apply/main.py, src/gobupload/compare/main.py, src/gobupload/storage/handler.py, src/tests/storage/test_handler.py, src/tests/storage/test_storage.py
Setting this on the connection leads to (vague) exceptions during CREATE TEMPORARY TABLE.
Instead, use the options during executing the query. ie: `session.execute(query, execution_options={..})`
passes end-2-end test
error:
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near \"CREATE\""
LINE 2: CREATE TEMPORARY TABLE nap_peilmerken_tmp ("
=> Remove execution_options from get_session

src/gobupload/apply/main.py, src/gobupload/relate/__init__.py, src/gobupload/relate/update.py, src/gobupload/storage/relate.py, src/tests/apply/test_apply.py, src/tests/relate/test_init.py, src/tests/relate/test_update.py, src/tests/storage/test_relate.py
- Stop generating CONFIRM events during relate
- Also remove exemption from apply for `rel`
- ANALYZE temporary tables after inserting
- simplify statements, remove StopIteration
=> Use psql TEMPORARY table in relate

src/gobupload/compare/main.py, src/gobupload/storage/handler.py, src/tests/compare/test_compare.py, src/tests/storage/test_handler.py
It seems `chunked` consumes every first element from the iterator, instead use sqlalchemy's `partitions`
=> Fix compare chunked iter

src/gobupload/relate/update.py, src/tests/relate/test_update.py
- Copy the necessary columns for the relate process to temporary tables. 
- In case of (very) wide src/dst tables this prevents copying data we don't need during relate.
- Moved initialisation of temp tables to seperate method
=> Select temp columns relate

src/alembic/versions/7c4e8e803d5b_update_brk2_schemas.py, src/requirements.txt
* Update core and add migrations for last BRK2 schemas
* Set core version to v2.12.0
* Drop legacy view if exists
=> Update core and add migrations for last BRK2 schemas (#1136)

src/alembic/env.py, src/gobupload/apply/event_applicator.py, src/gobupload/config.py, src/gobupload/storage/handler.py, src/gobupload/utils.py, src/tests/storage/test_handler.py, src/tests/test_utils.py
~~needs rebase https://github.com/Amsterdam/GOB-Upload/pull/1144~~
- tweaking the`executemany` engine parameters did the trick
SQLAlchemy will group as much as possible in 1 UPDATE statement. 
The INSERTS were already grouped in batches of 10_000, disable the `insertmanyvalues` feature though. We don't need to use `RETURNING`.
- Fix: use URL.create in constructing connection string (required for sqlalchemy v2)
- Remove unused GargabeCollector class
=> Batch updates + fix alembic connection string

src/gobupload/apply/main.py, src/gobupload/compare/event_collector.py, src/gobupload/storage/handler.py, src/gobupload/utils.py, src/tests/apply/test_apply.py, src/tests/storage/test_handler.py
- Replace DISTINCT call to events table with result from pg_tables
- Reduce usage of server side cursor, should not be necessary
- Use datetime parameter in apply_confirms query
- lower max bulk_confirm to 10.000
=> Misc storage handler fixes

src/gobupload/storage/handler.py, src/tests/storage/test_handler.py
Prevents applying confirms if date confirmed is already up-to-date, saving database resources
=> Only update date_confirmed if necessary

src/gobupload/storage/handler.py, src/gobupload/update/main.py, src/tests/storage/test_handler.py
events.contents looks like this now:
```json
"{\"modifications\": [{\"key\": \"gebruiksdoel\", \"old_value\": [{\"code\": 5, \"omschrijving\": \"industriefunctie\"}, {\"code\": 1, \"omschrijving\": \"woonfunctie\"}], \"new_value\": [{\"code\": 1, \"omschrijving\": \"woonfunctie\"}, {\"code\": 5, \"omschrijving\": \"industriefunctie\"}]}, {\"key\": \"_hash\", \"old_value\": \"d9eb845571227ef05b48918c3db23c8e\", \"new_value\": \"f9f1575c7e82f95bf0a1a2ba4a6e650a\"}], \"_hash\": \"f9f1575c7e82f95bf0a1a2ba4a6e650a\", \"_last_event\": 1695819809, \"_tid\": \"0363010000593037.5\"}"
```
Don't implicitely cast values using postgresql `to_json`, instead with `::jsonb` (value is already valid json)
result example:
```json
{"entity": {"_id": "SV00001071_GR01GR.pdf", "_hash": …
```
=> Fix: prevent escaping json values in contents from events
