src/gobcore/data_types/__init__.py
src/gobcore/data_types/db_util.py
src/gobcore/data_types/gob_types.py
src/gobcore/events/__init__.py
src/gobcore/events/gob_events.py
src/gobcore/message_broker/async_message_broker.py
src/gobcore/message_broker/message.py
src/gobcore/models/event.py
src/gobcore/models/metadata.py
src/gobuploadservice/__main__.py
src/gobuploadservice/compare.py
src/gobuploadservice/config.py
src/gobuploadservice/storage/init_entity.py
src/gobuploadservice/storage/init_event.py
src/gobuploadservice/storage/init_storage.py
src/gobuploadservice/update.py

Provide for additional comments.
The compare and upload logic is, although small, quite complex.
The additional comments will help to understand and maintain the logic

Additional documentation

---

.gitignore
src/requirements.txt
src/tests/fixtures.py

Update gobcore version to fix issues with GOBTypes

Update gobcore requirement

---

docker-compose.yml
src/gobuploadservice/__init__.py
src/gobuploadservice/storage/db_models/event.py
src/gobuploadservice/storage/storage_handler.py

Use the GOBTypeJSONEncoder to fix issues with Decimal. Add the database overrides to the docker-compose for local testing and improve the print output of events.

Fix storage issues

---

src/gobuploadservice/__init__.py
src/gobuploadservice/compare.py
src/gobuploadservice/update.py
src/requirements.txt
src/tests/fixtures.py
src/tests/test_compare.py
src/tests/test_update.py

Logging was added to update and compare functions. Logging had to be disabled in tests to prevent trying to connect to rabbitmq.

Process monitoring

---

src/requirements.txt

Update to gobcore to include rollagen enhanced view

Update gobcore to v0.4.8

---

src/gobupload/storage/handler.py
src/requirements.txt

Small fix to rename event to events

Update gobcore to use the latest model

---

src/requirements.txt

Needed to update the database with the latest views

Update gobcore to the latest version

---

src/gobupload/compare.py
src/gobupload/storage/handler.py
src/gobupload/update.py
src/tests/fixtures.py

Improve logging by showing GOB database user
Add catalogue to logging

Include GOB database user and catalogue in logging

---

src/gobupload/storage/handler.py
src/requirements.txt

Update gobcore for latest views

---

src/gobupload/relations.py
src/requirements.txt
src/tests/test_relations.py

Function added to relate from an entity to another entity through multiple steps

Chained relations added to relate functions

---

src/gobupload/compare.py
src/gobupload/storage/handler.py
src/requirements.txt
src/test.sh
src/tests/test_compare.py

An import may depend on any other sources
The dependencies are checked and if the check fails
the further processing is cancelled and an error is logged

Fail on missing dependencies

---

src/gobupload/relations.py
src/tests/test_relations.py

Each application has its own relation characteristics

Relate collections per application

---

src/requirements.txt

Needed to fix datetime isoformat problems

Update gobcore to latest version

---

src/gobupload/update.py
src/requirements.txt
src/tests/test_update.py

Release 2019-01-25

---

src/requirements.txt

Latest gobcore

---

src/gobupload/__init__.py
src/gobupload/compare.py
src/gobupload/enrich.py
src/gobupload/update.py
src/tests/fixtures.py
src/tests/test_enrich.py
src/tests/test_update.py

GOB logging for incoming messages. Initial information is stored
for subsequent logging.
Added tests to increase test coverage.

FIXES #513 https://datapunt.atlassian.net/browse/GOB-513

---

src/gobupload/compare.py
src/gobupload/storage/handler.py
src/gobupload/storage/queries.py
src/gobupload/update.py
src/requirements.txt
src/test.sh
src/tests/storage/test_handler.py
src/tests/test_compare.py

The state logic is encapsulated by GOB-Core

Use model has_states logic

---

src/tests/test_update.py

Fix small error in unit test of update

Fix unit test

---

src/gobupload/enrich.py
src/tests/test_enrich.py

Take only active underlying entities

Union of geometries

---

src/gobupload/relate/__init__.py
src/requirements.txt

Set prefetch count to 1 to solve duplication of messages

Update GOB Core version, Prefetch count 1

---

src/gobupload/relate/relate.py
src/gobupload/storage/relate.py
src/tests/relate/test_init.py
src/tests/relate/test_relate.py

Simplified relate module
Solved issues for GOB.ManyReference relations

Fix GOB.ManyReference issues

---

src/requirements.txt

Use geometry to determine relationships between bouwblokken and buurten

Release 20190403

---

src/gobupload/compare.py
src/gobupload/storage/handler.py
src/tests/storage/test_handler.py

Preparation for streaming of compare step

Write to temporary table per entity

---

src/gobupload/relate/apply.py

When multiple relations are found for a single reference log a warning to be able to check for data errors

Log warnings for single references with multiple values

---

src/gobupload/storage/relate.py
src/tests/storage/test_relate.py

The used query was performing slow due to not using the indexes

Update relation last change query

---

src/gobupload/compare/main.py
src/requirements.txt

ProgressTicker was added to the compare step of the relate/compare/upload process. Update to gobcore to remove the heeft_brondocumenten relation

Remove heeft_brondocumenten from BAG and add progressTicker

---

src/gobupload/compare/main.py
src/tests/compare/test_compare.py

The geometry is derived from the geometry of the buurten

GGW and GGP gebieden depend on buurten

---

src/gobupload/relate/apply.py
src/tests/relate/test_apply.py
src/tests/relate/test_init.py

Show all entities with a bronwaarde that could not be matched with another entity

Show warnings for any missing relations

---

src/requirements.txt

Allow long lasting db operations
without timing out on the message broker

Update core - Increase pika timeouts

---

src/gobupload/relate/__init__.py
src/gobupload/storage/relate.py
src/tests/relate/test_init.py
src/tests/relate/test_relate.py
src/tests/storage/test_relate.py

Using the new relate logic where relations are updated
directly in the entities

Check relations

---

src/gobupload/relate/__init__.py

Export entity in header to allow for the frontend to display
the name of the catalog that is being imported

Show entity

---

src/gobupload/relate/__init__.py
src/gobupload/relate/relate.py
src/gobupload/storage/relate.py
src/tests/relate/test_init.py
src/tests/relate/test_relate.py
src/tests/storage/test_relate.py

Update only the changed rows
Update rows in chunks of max 100,000 rows
Show progress logging

Improve performance of relate

---

src/gobupload/storage/relate.py
src/tests/storage/test_relate.py

Run update until updates count has been reached

---

src/alembic/versions/3d1d3ba6873a_fix_bgt_model.py
src/requirements.txt

Volgnummer and registratiedatum have now been autogenerated as a state field

Change ONW model

---

src/gobupload/storage/execute.py
src/gobupload/storage/relate.py
src/gobupload/storage/update_table.py
src/test.sh
src/tests/storage/test_relate.py
src/tests/storage/test_update_table.py

Will write some more tests to verify consistency between source and relation tables.

GOB-1051 Update relation tables parallel to source tables

---

src/gobupload/compare/main.py
src/gobupload/config.py
src/gobupload/storage/handler.py
src/gobupload/storage/queries.py

Partial uploads are handled by simply skipping the derivation of DELETE events

Partial upload

---

src/requirements.txt

To fix woonplaatscode in enhanced uva2 views.

Update core to v0.11.9

---

src/requirements.txt

For verblijfsobjecten enhanced uva2 view change.

Update core to v0.11.11

---

src/requirements.txt

To add gebruiksdoel columns to verblijfsobjecten enhanced uva2 view.

Update core to v0.11.13

---

src/gobupload/storage/handler.py

Put all protected code in a try-except block to ensure that the lock gets always released

Protect create index part 1

---

src/requirements.txt

Change required to create enhanced views for WKPB

Changed reference GOBCore to 0.13.14

---

src/gobupload/storage/handler.py
src/gobupload/update/event_applicator.py
src/tests/storage/test_handler.py

With temporary compatibility fix

Fix bug insert events

---

src/gobupload/update/main.py

Include extra logging to show the id of the last event for a given model and the id of the last event that has been applied on the model

Log events and model status

---

src/gobupload/compare/enrich.py
src/tests/compare/test_enrich.py

Fixed some issues that appeared while making the end-2-end tests

Improve autoid

---

src/gobupload/relate/table/update_table.py
src/tests/relate/table/test_update_table.py

Will write a migration that checks for null values in relation tables, to clear those tables and events.

PGB-1197 Ignore NULL bronwaardes for single references

---

src/gobupload/relate/table/update_table.py
src/tests/relate/table/test_update_table.py

The src-dst_volgnummer_begin_geldigheid contained all possible intervals
Only the intervals for the entities that have changed are needed
In non-initial update mode the output is used twice
For larger collections the output is now reduced from millions of rows to just some rows
The SQL statements that have been touched have been improved by adding comments
This makes it easier to debug and understand the logic

Fix bug in relate query, improve SQL comments

---

src/gobupload/relate/table/update_table.py
src/tests/relate/table/test_update_table.py

The src-dst_volgnummer_begin_geldigheid contained all possible intervals
Only the intervals for the entities that have changed are needed
In non-initial update mode the output is used twice
For larger collections the output is now reduced from millions of rows to just some rows
The SQL statements that have been touched have been improved by adding comments
This makes it easier to debug and understand the logic

Release fix bug in relate query, improve SQL comments

---

src/requirements.txt

Fixes issue with QA-Catalog updates

Update GOB-Core version

---

src/requirements.txt

To handle validity date and skip GOBPrepare

Release update GOB-Core

---

src/requirements.txt

Automated update of GOB-Core to its latest version

Update GOB-Core version from v0.15.6b to v0.15.7

---

src/gobupload/storage/relate.py
src/requirements.txt
src/tests/storage/test_relate.py

Creates data warnings for conflicting relations.

PGB-975 Catch relation conflict messages in QA Issues

---

src/requirements.txt

Automated update of shared lib(s) to their latest version

Update GOB-Core v0.16.4 to v0.16.5

---

src/gobupload/config.py
src/gobupload/relate/__init__.py
src/gobupload/relate/update.py
src/tests/relate/test_init.py
src/tests/relate/test_update.py

Add option for full relate to prevent the need to clear the relation table

PGB-1627 Fix bug that deleted valid relations

---

src/gobupload/relate/update.py
src/tests/relate/test_update.py

Adds pagination to initial relates to avoid overloading the database server with the huge initial queries.

Add pagination to speed up initial relates

---

src/gobupload/relate/update.py
src/tests/relate/test_update.py

Moved back the functionality last week, but had removed the tests in the meanwhile.
Fixed it now :)

Fix funny (IMPOSSIBLE) logic in relate

---

src/requirements.txt

Adds soortobject to bag verblijfsobjecten enhanced views

Update GOB-Core to v0.17.10e

---

src/alembic/versions/0ef7b437e56e_remove___prefix.py
src/requirements.txt

Migrate database to remove underscores

---

src/gobupload/storage/handler.py
src/requirements.txt

Additionally: update core and fix long running queries in development

Add support for 'update' mode from gob-core

---

docker-compose.yml
src/Dockerfile
src/gobupload/__main__.py
src/gobupload/apply/main.py
src/gobupload/compare/main.py
src/gobupload/relate/__init__.py
src/gobupload/update/main.py
src/requirements.txt
src/test.sh
src/tests/apply/test_apply.py
src/tests/compare/test_compare.py
src/tests/test_main.py
src/tests/test_update.py

[AB#49818](https://dev.azure.com/CloudCompetenceCenter/7755cdf4-1859-48c5-b954-fd6c8e46fe52/_workitems/edit/49818)

49818 standalone upload revised

---

Jenkinsfile
README.md
src/.dockerignore
src/.jenkins/test/docker-compose.yml
src/Dockerfile
src/pytest.ini
src/requirements.txt
src/test.sh
src/tests/test_alembic_utils.py

Alembic update; fix deprecation warnings.

Run as user datapunt.

---

README.md
src/alembic/README
src/alembic/versions/cda2005bcf0e_meetbouten_to_amschema.py
src/requirements.txt

Need to set Core version after this PR is merged: https://github.com/Amsterdam/GOB-Core/pull/675

Add migration for meetbouten amsterdam schema

---

README.md
src/alembic/README
src/alembic/versions/cda2005bcf0e_meetbouten_to_amschema.py
src/requirements.txt

* Add migration for meetbouten amsterdam schema
* Update requirements.txt

Add migration for meetbouten amsterdam schema (#971)

---

src/gobupload/__main__.py
src/requirements.txt

Rename relate_prepare workflow logger to relate

---

README.md
src/alembic/README
src/alembic/versions/cda2005bcf0e_meetbouten_to_amschema.py
src/gobupload/__main__.py
src/requirements.txt

- Add migration for meetbouten amsterdam schema
- Rename relate_prepare workflow logger to relate

Add migration meetbouten + rename relate_prepare

---

src/alembic/versions/0ce50938f539_gebieden_begin_eind_geldigheid_datetime.py

This is a generalized version of https://github.com/Amsterdam/GOB-Upload/pull/976

Don't drop views where viewowner is `azure_superuser`

---

src/.flake8
src/gobupload/__init__.py
src/gobupload/storage/handler.py
src/gobupload/storage/materialized_views.py
src/gobupload/storage/relate.py
src/test.sh
src/tests/storage/test_handler.py
src/tests/storage/test_materialized_views.py
src/tests/storage/test_relate.py

* Refactored storage (GOBModel)
* Test script: coverage 95%; simplified flake8 config

Storage gob model

---

CODEOWNERS
src/.flake8
src/alembic/versions/0ce50938f539_gebieden_begin_eind_geldigheid_datetime.py
src/gobupload/__init__.py
src/gobupload/storage/handler.py
src/gobupload/storage/materialized_views.py
src/gobupload/storage/relate.py
src/requirements.txt
src/test.sh
src/tests/storage/test_handler.py
src/tests/storage/test_materialized_views.py
src/tests/storage/test_relate.py

* Test script: simplified flake8 config

Refactored storage.

---

src/gobupload/__main__.py
src/gobupload/relate/__init__.py
src/gobupload/storage/handler.py
src/requirements.txt
src/tests/relate/test_init.py
src/tests/storage/test_handler.py
src/tests/test_main.py

- Raise error on migration failure
- Warn when relations are skipped in preparing relate

Extra error and warning

---

src/gobupload/relate/__init__.py
src/tests/relate/test_init.py

* Refactored relate __init__ for gob_model.
* Leaner message functions.

Refactored relate __init__ for gob_model. (#988)

---

src/.flake8
src/gobupload/__main__.py
src/gobupload/compare/populate.py
src/gobupload/relate/__init__.py
src/gobupload/relate/update.py
src/requirements.txt

* Update Core (and Alembic).
* Style check updates.

BRK2 TNG tid change. (#1022)

---

src/gobupload/storage/handler.py
src/gobupload/update/event_collector.py
src/gobupload/update/main.py
src/requirements.txt
src/tests/storage/test_handler.py
src/tests/update/test_event_collector.py
src/tests/update/test_update.py

- simplify EventCollector
- Remove BULKCONFIRM logic
- Use sqlalchemy bulkinsert instead of raw sql

Update store events

---

src/gobupload/apply/main.py
src/gobupload/storage/handler.py
src/tests/storage/test_handler.py

- Passes end-to-end test locally

Add option to reflect a subset of tables

---

src/gobupload/storage/handler.py
src/tests/storage/test_handler.py
src/tests/storage/test_storage.py

No need for random suffix (just `_tmp`) on the temp table name, due to session separation.
Make sure the table is also removed from the metadata at the end of a session.

Remove random suffix for temp tables

---

src/gobupload/apply/main.py
src/gobupload/compare/event_collector.py
src/gobupload/storage/handler.py
src/requirements.txt
src/tests/apply/test_apply.py
src/tests/storage/test_handler.py
src/tests/update/test_main.py

- refactor apply_confirms
- Use UPDATE.. FROM instead of WHERE..IN
- Show progress during bulkconfirm
- Increase batchsize to 100.000
Needs GOB-Core update https://github.com/Amsterdam/GOB-Core/pull/708

Refactor apply_confirm_events

---

src/gobupload/compare/entity_collector.py
src/gobupload/compare/main.py
src/tests/compare/test_compare.py
src/tests/compare/test_entity_collector.py

- ContentsWriter.open/close doesn't exist anymore
- Refactor compare function
- e2e_test passed

Fix contextmanagers in compare

---

src/gobupload/storage/handler.py
src/tests/storage/test_handler.py

Using streaming was causing long locks on the events table, which prevent inserting new events.

Use eventid pagination during apply

---

src/alembic/versions/a7a44cb317a7_muurvlak_coordinaten_type_integer.py

Also drop enhanced views:
- `meetbouten_referentiepunten_enhanced`
- `nap_peilmerken_enhanced`

Also drop enhanced views.

---

Jenkinsfile
azure-pipelines.yml

Add azure-pipelines.yml

---

src/gobupload/relate/update.py
src/tests/relate/test_update.py

* Select necessary columns for relate process
* Refactor Relater.__init__
- move temp table creation to seperate method
* Add temp table creation test

Select temp columns relate (#1132)

---

src/gobupload/relate/update.py
src/tests/relate/test_update.py

Also add _gobid to src columns

Include destination_attribute column for self referencing relations

---

src/gobupload/storage/handler.py
src/tests/storage/test_handler.py

Goal: Cancel running query on process restart
Not tested yet if query stops

Wrap apply_confirms in a session

---

src/gobupload/storage/handler.py
src/tests/storage/test_handler.py

disable implicit returning
nu wel getest met e2e

Fix inserting events

---

src/Dockerfile
src/gobupload/storage/handler.py
src/tests/storage/test_handler.py

Index creation is currently not persisted due to rollback

Fix committing index drop and create

---

src/Dockerfile
src/requirements.txt

Update to Python 3.9.18 (latest).

Non Azure dataset GOB models (consolidation). (#1180)

---

src/alembic/versions/097fd62ade0a_brk1_omzetten_naar_brk2_gemeentes.py

drop tables with cascade fixed

drop tables with cascade fixed

---

src/alembic/versions/097fd62ade0a_brk1_omzetten_naar_brk2_gemeentes.py

drop table cascade fix poging 2

drop table cascade fix poging 2

---

src/alembic/versions/097fd62ade0a_brk1_omzetten_naar_brk2_gemeentes.py

drop tables cascade fixed
